#!/bin/bash

FILE=fgsrs
BUILDPATH=./target/release
EXEC=./fgsrs

if [ ! -f "$FILE" ]; then
    # EXECUTABLE DOESN'T EXIST YET, WE SHOULD BUILD
    cargo build --release
    cp $BUILDPATH/$FILE $EXEC
    chmod +x $EXEC
fi

$EXEC "$@"